version: 2.1
orbs:
    codecov: codecov/codecov@3.3.0
jobs:
    build:
        docker:
            - image: 'cimg/node:lts-browsers'
        resource_class: large
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - 'v1-dependencies-{{ checksum "package-lock.json" }}'
                    - v1-dependencies-
            - run:
                name: Install dependencies
                command: npm install
            - save_cache:
                key: 'v1-dependencies-{{ checksum "package-lock.json" }}'
                paths:
                    - node_modules
            - run:
                name: Build library
                command: npm run release
            - run:
                name: Run unit tests
                command: npm run test
            - codecov/upload
