version: 2.1
orbs:
    codecov: codecov/codecov@3.3.0
jobs:
  publish:
    docker:
      - image: 'cimg/node:lts-browsers'
    resource_class: large
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "pnpm-lock.yaml" }}'
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: pnpm install
      - save_cache:
          key: 'v1-dependencies-{{ checksum "pnpm-lock.yaml" }}'
          paths:
            - node_modules
      - run:
          name: Build library
          command: pnpm run prepublish
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            pnpm publish

workflows:
  main:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - master
